# Generated by Django 5.0.7 on 2024-07-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of', models.CharField(choices=[('movie', 'movie'), ('serie', 'serie'), ('documentary', 'documentary'), ('other', 'other')], default='other', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, related_name='media', to='media.genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
